"""Add scix_ui column with default False

Revision ID: 4cc89f2f896b
Revises: 21bf40903ec3
Create Date: 2025-05-07 15:59:58.986287

"""

# revision identifiers, used by Alembic.
revision = '4cc89f2f896b'
down_revision = '21bf40903ec3'

from alembic import op
import sqlalchemy as sa

                               
from sqlalchemy.dialects import postgresql

def upgrade():
    #with app.app_context() as c:
    #   db.session.add(Model())
    #   db.session.commit()
        
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myads', sa.Column('scix_ui', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.execute("UPDATE myads SET scix_ui = FALSE WHERE scix_ui IS NULL")
    op.alter_column('myads', 'scix_ui', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('myads', 'scix_ui')
    # ### end Alembic commands ###
