"""Add get_other_papers flag to myads table

Revision ID: 717c2970ff42
Revises: 4cc89f2f896b
Create Date: 2025-07-15 16:14:53.689180

"""

# revision identifiers, used by Alembic.
revision = '717c2970ff42'
down_revision = '4cc89f2f896b'

from alembic import op
import sqlalchemy as sa

                               
from sqlalchemy.dialects import postgresql

def upgrade():
    #with app.app_context() as c:
    #   db.session.add(Model())
    #   db.session.commit()
        
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myads', sa.Column('get_other_papers', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('myads', 'get_other_papers')
    # ### end Alembic commands ###
