"""Add get_other_papers_flag

Revision ID: dcda14f51cff
Revises: 4cc89f2f896b
Create Date: 2025-07-09 12:36:39.558910

"""

# revision identifiers, used by Alembic.
revision = 'dcda14f51cff'
down_revision = '4cc89f2f896b'

from alembic import op
import sqlalchemy as sa

                               
from sqlalchemy.dialects import postgresql

def upgrade():
    #with app.app_context() as c:
    #   db.session.add(Model())
    #   db.session.commit()
        
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myads', sa.Column('get_other_papers', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.execute("UPDATE myads SET get_other_papers = TRUE WHERE get_other_papers IS NULL")
    op.alter_column('myads', 'get_other_papers', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('myads', 'get_other_papers')
    # ### end Alembic commands ###
