"""Add get_other_papers flag to myads table

Revision ID: f1a2b3c4d5e6
Revises: 4cc89f2f896b
Create Date: 2025-01-11 12:00:00.000000

"""

# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = '4cc89f2f896b'

from alembic import op
import sqlalchemy as sa

                               
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myads', sa.Column('get_other_papers', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.execute("UPDATE myads SET get_other_papers = TRUE WHERE get_other_papers IS NULL")
    op.alter_column('myads', 'get_other_papers', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('myads', 'get_other_papers')
    # ### end Alembic commands ### 